### ISSUE TITLE
uber calibration groups issue

### ISSUE THREAD

**Issue by topepo** [tidymodels/probably#104]
There are `group` arguments to the `cal_plot_*` and `cal_estimate_*` functions.  There are overlaping issues regarding groups (#79,  #92,#98, #100). Looking at these, we should have a more systematic approach rather than multiple refactors that might overlap. 

I think that we should only enable group-by processing when the input is a data frame (and not an object generated by the tune package). We should default to using .config for tune objects when there are multiple configurations (and `NULL` otherwise).

## Change 1

In the many functions it is set in both the S3 generic and also in an internal helper called `tune_results_args()`.

- For non-tune S3 generics, allow the user to set it as an argument and validate it in the generic with a helper function. 
- For tune generics, give no `group` argument and set `group` to `.config` if there are multiple configurations. 

The logic for `group` should not be in multiple places so it should be taken out of `tune_results_args()`. 

## Change 2

The user-facing argument should be called `.by` to be consistent with new dplyr syntax.  It should only accept a single, categorical column in the data.

**Comment by EmilHvitfeldt** [comment]
# change 3

error if grouped data.frame passed to functions. Refer to `.by` argument
