### ISSUE TITLE
Can threshold_perf() be used for multiclass?

### ISSUE THREAD

**Issue by DavisVaughan** [tidymodels/probably#15]
https://twitter.com/dvaughan32/status/1076299165083287552

**Comment by oarmstrong95** [comment]
Hi - is there any documentation on how to use threshold_perf() for multiclass ?

**Comment by topepo** [comment]
No. That methodology only applies to two-class problems.

**Comment by DavisVaughan** [comment]
Should this be closed then @topepo?

**Comment by topepo** [comment]
yep
