### ISSUE TITLE
Error: package or namespace load failed for ‘probably’:  object ‘vec_unspecified_cast’ is not exported by 'namespace:vctrs'

### ISSUE THREAD

**Issue by John-Gal** [tidymodels/probably#20]
Hi,

A note to say that a recent install from GitHub leads to the following error on load 

library(probably)
Error: package or namespace load failed for ‘probably’:
 object ‘warn_lossy_cast’ is not exported by 'namespace:vctrs'

Package vctrs is up-to-date 

Cheers,

John

**Comment by topepo** [comment]
What version of `vctrs` are you using? Can you try using the CRAN version?

**Comment by John-Gal** [comment]
I'm using vctrs version 0.1.0.9003

Re-installed with the CRAN version and now library(probably) shows a slightly different error

Error: package or namespace load failed for ‘probably’:
 object ‘vec_unspecified_cast’ is not exported by 'namespace:vctrs'

**Comment by DavisVaughan** [comment]
Are you sure you restarted R after installing? They just removed that function from vctrs 5 days ago, so that error message implies that you still have the dev version loaded

**Comment by John-Gal** [comment]
I was restarting R from within Rstudio, but restarting Rstudio and starting completely from fresh did the trick. Thank you!
