### ISSUE TITLE
Is it possible to specify a metric_set within threshold_perf?

### ISSUE THREAD

**Issue by kdpsingh** [tidymodels/probably#25]
Is it possible to specify a metric_set within threshold_perf?

By default, it looks at sens, spec, j_index, and distance. Is it possible to look at other measures across a range of threshold probabilities?

For example, accuracy, positive predictive value (precision), negative predictive value would be great to be able to access.

One way to accomplish this would be to embed a metric_set argument within threshold_perf().

Thanks for your consideration!

Karandeep

**Comment by DavisVaughan** [comment]
I think that sounds reasonable. The current implementation uses a metric set already, so it would make sense to allow a user supplied one

**Comment by anhthyngo** [comment]
Where exactly can you supply a different metric? For example: precision, recall, and f_measure?

**Comment by DavisVaughan** [comment]
It is currently not possible

**Comment by szego** [comment]
I added a `metrics` argument that accepts a yardstick metric set:

https://github.com/szego/probably/commit/94c6189e173c510377ecfe54665967c41f7ea10a

Is the team interested in a pull request for this?

**Comment by DavisVaughan** [comment]
@szego if you are still interested in making a PR, go ahead and I will take a look when I circle back to work on probably

**Comment by sandeshregmi** [comment]
Hello @DavisVaughan,
Have you gotten a chance to look at `metrics` argument @szego added?
