### ISSUE TITLE
issue with make_two_class_pred() with glm model

### ISSUE THREAD

**Issue by paullevchuk** [tidymodels/probably#30]
I am using glm model from parsnip / workflow scheme. 

To make it works properly, I did the following things:
```
data <- read_csv("aha.csv", col_types = cols()) %>% 
  # (1) glm requires a failure to be the 1st level
  mutate(truth = factor(buyer_90d, levels = c(0, 1), labels = c("NB", "Buyer")))
```

```
library(yardstick)
# (2) reconfigure yardstick to take success from the 2nd level
options(yardstick.event_first = FALSE)
```

But when I tried to make hard predictions via `make_two_class_pred()` it's failed. 
It seems like it used 1st level as a success despite the statement in point (2).

To fix it I wrote code lie this:
```
data_pred <- data_pred %>%
  mutate(.pred = make_two_class_pred(estimate = .pred_Buyer, 
                                     levels = levels(truth), 
                                     threshold = max_j_index_thre) %>% probably::as.factor(),
         .pred2 = if_else(.pred_Buyer > max_j_index_thre, "Buyer", "NB") %>% fct_relevel("NB")) 
```

**Comment by DavisVaughan** [comment]
Can you please provide a reproducible example that uses a toy data set rather than a csv?

**Comment by DavisVaughan** [comment]
I don't think that `make_two_class_pred()` should be aware of this yardstick option. The documentation for it states that the `estimate` column needs to be class probabilities for the first level in `levels`. Since your first level of `truth` is `"NB"` and you have a binary classification problem, I imagine you could do:

`make_two_class_pred(estimate = 1 - .pred_Buyer, levels = levels(truth))`

Note that, on the other hand, `threshold_perf()` is aware of the yardstick option.

``` r
suppressPackageStartupMessages({
  library(yardstick)
  library(probably)
})

# the default
options(yardstick.event_first = TRUE)

sens(two_class_example, truth, predicted)
#> # A tibble: 1 x 3
#>   .metric .estimator .estimate
#>   <chr>   <chr>          <dbl>
#> 1 sens    binary         0.880
threshold_perf(two_class_example, truth, Class1, thresholds = 0.5)
#> # A tibble: 4 x 4
#>   .threshold .metric  .estimator .estimate
#>        <dbl> <chr>    <chr>          <dbl>
#> 1        0.5 sens     binary        0.880 
#> 2        0.5 spec     binary        0.793 
#> 3        0.5 j_index  binary        0.673 
#> 4        0.5 distance binary        0.0571

options(yardstick.event_first = FALSE)

sens(two_class_example, truth, predicted)
#> # A tibble: 1 x 3
#>   .metric .estimator .estimate
#>   <chr>   <chr>          <dbl>
#> 1 sens    binary         0.793
threshold_perf(two_class_example, truth, Class2, thresholds = 0.5)
#> # A tibble: 4 x 4
#>   .threshold .metric  .estimator .estimate
#>        <dbl> <chr>    <chr>          <dbl>
#> 1        0.5 sens     binary        0.793 
#> 2        0.5 spec     binary        0.880 
#> 3        0.5 j_index  binary        0.673 
#> 4        0.5 distance binary        0.0571
```

<sup>Created on 2020-06-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by paullevchuk** [comment]
Sorry, that I haven't provided an example. Your solution (1 - pred) is good enough for me.

But I still think that there is some inconsistency between `yardstick` and `probably` and your example with threshold_perf() somehow proved it.
