### ISSUE TITLE
Add a model "calibration" step.

### ISSUE THREAD

**Issue by coforfe** [tidymodels/probably#36]
Hello Max,

Firstly, thanks to both of you for this excellent reference material about tidymodels.

I have just checked if there is any section about **model calibration** but I could not find any. Since you covered that in `caret`, are you considering to include it as another possible step in a model workflow ?.

Also, it would be fantastic if you could include some kind of suggestion to calibrate _multi-class_ models, in the same was as you already covered performance metrics for this kind of models.

Thanks again!
Carlos Ortega

**Comment by topepo** [comment]
Calibration is in the latest version of probably. [Here](https://www.tidymodels.org/learn/models/calibration/) is an article about some of them.
