### ISSUE TITLE
Reliability Diagrams, Calibration Error, and Temperature Scaling

### ISSUE THREAD

**Issue by simonschoe** [tidymodels/probably#59]
Hi there,

great work on the package so far! I was wondering if you are planning to extend the types of calibration diagnostics:

- Reliability Diagrams (as outlined in [On Calibration of Modern Neural Networks](https://arxiv.org/abs/1706.04599))
- Expected Calibration Error (same paper, related to / derived from Reliability Diagrams)

EDIT: Now that I think about it, isn't a reliability diagram exactly the same plot (using bars instead of a `geom_line()`)?

The former should be easily implemented, right?
```
segment_logistic %>% 
  mutate(bin = cut(.pred_good, seq(0, 1, 0.1), labels = F),
         .pred_class = if_else(.pred_good > 0.5, "good", "poor")) %>% 
  summarise(accuracy =mean(if_else(Class == "good", 1L, 0L)), .by = bin) %>% 
  ggplot(aes(x = bin, y = accuracy)) +
  geom_col() +
  geom_abline(intercept = 0, slope = 0.1, lty = "dashed") +
  scale_y_continuous(limits = c(0L, 1L)) +
  theme_minimal()
```

Moreover, do you plan to integrate actual postprocessing steps in the package as well? I am currently working with temperature scaling (in the context of neural networks). I guess its conceptually related to what you were already outlining in the [blog post](https://www.tidyverse.org/blog/2022/11/model-calibration/#preparing-for-the-next-stage).

![temp_1](https://user-images.githubusercontent.com/53626067/209098141-8355b7e6-8e0b-425d-93a7-3b2b3e76aef7.png )
![temp_1 25](https://user-images.githubusercontent.com/53626067/209098134-b11a6539-c539-4b0e-9a78-46199c65802c.png)
![temp_1 5](https://user-images.githubusercontent.com/53626067/209098129-77fc554d-8373-44be-85c8-6957d912e15b.png)
![temp_1 75](https://user-images.githubusercontent.com/53626067/209098137-6021fd4a-6504-4148-b7d8-6f25765d5418.png)
![temp_2](https://user-images.githubusercontent.com/53626067/209098145-27bfeb27-28ae-44cb-a1f2-28d657148dac.png)

Keep on with the great work!

Best,
Simon

**Comment by topepo** [comment]
A lot of this is in the current GH version. Let us know if you see anything missing.
