### ISSUE TITLE
Optimize the prediction threshold so that minimizes the costs associated with type I and II errors

### ISSUE THREAD

**Issue by DiabbZegpi** [tidymodels/probably#88]
There is an equation that associated type I and II error rates with the cost of committing them.
For example, in a customer churn problem, the cost of type-I error could be $10 and the cost of type-II error be $200, because of the promotions and missed  income, respectively. There is a short equation which its derivative, when projected to a corner of the ROC curve, gives the optimal threshold for minimizing the aforementioned cost.

I've read about this method in a paper few years ago, but can't find it now. Is this equation familiar to anybody?

**Comment by topepo** [comment]
You might be thinking of the papers by Drummond and crew on [_cost curves_](https://scholar.google.com/scholar?hl=en&as_sdt=0%2C7&q=Drummond+%22cost+curve%22&btnG=).

**Comment by topepo** [comment]
...which we currently do not do. You are welcome to add a PR though.
